[project]
name = "snowflake-document-agent"
version = "0.5.0"
description = "Python ELT processes to incrementally load document files into Snowflake Document Agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-evaluation>=0.4.1",
    "charset-normalizer>=3.4.4",
    "lxml>=5.4.0",
    "mammoth>=1.11.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "pip-system-certs>=5.3",
    "pyyaml>=6.0.2",
    "snowflake-connector-python>=3.12.0",
    "requests>=2.31.0",
    "tenacity>=8.2.0",
    "xlrd>=2.0.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.9.0",
    "snowflake-cli>=3.14.0",
]

[project.scripts]
ingest-local = "snowflake_document_agent.ingest_local:main"
ingest-opentext = "snowflake_document_agent.ingest_opentext:main"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.9.0",
    "snowflake-cli>=3.14.0",
    "responses>=0.24.0",
]

[tool.ruff]
line-length = 120

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
